apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "azurekeyvaults.btungut.io"
  labels:
    {{- include "azure-keyvault-secret-operator.labels" . | nindent 4 }}
spec:
  group: "btungut.io"
  scope: Cluster
  names:
    plural: "azurekeyvaults"
    singular: "azurekeyvault"
    kind: "AzureKeyVault"
    shortNames:
      - "akv"
      - "azurekv"
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "An Azure KeyVault reference which is responsible to sync its contents"
          properties:
            spec:
              type: object
              required: ["name", "resourceGroup", "servicePrincipal", "objects"]
              properties:
                name:
                  type: string
                  description: "Azure KeyVault resource name"
                resourceGroup:
                  type: string
                  description: "Resource group which includes Azure KeyVault"
                syncVersion:
                  type: integer
                  description: "Optional version value which is being tracked by operator to identify that whether secrets need to be updated or not"
                  minimum: 1
                  default: 1
                servicePrincipal:
                  type: object
                  description: "Authorized service principal which is used against Azure APIs"
                  required: ["secretName", "secretNamespace","tenantIdField", "clientIdField", "clientSecretField"]
                  properties:
                    secretName:
                      type: string
                      description: "Secret name which includes service principal credentials"
                    secretNamespace:
                      type: string
                      description: "Secret namespace which includes service principal credentials."
                    tenantIdField:
                      type: string
                      description: "The data/field name that correspond to Tenant Id of Azure"
                    clientIdField:
                      type: string
                      description: "The data/field name that correspond to Client Id (app id) of service principal"
                    clientSecretField:
                      type: string
                      description: "The data/field name that correspond to Client Secret (password) of service principal"
                objects:
                  type: array
                  description: "List of Azure KeyVault contents and Kubernetes secrets which needs to be synced"
                  items:
                    type: object
                    required: ["name", "type", "copyTo"]
                    properties:
                      name:
                        type: string
                        description: "Name of Azure KeyVault content"
                      type:
                        type: string
                        description: "Type of Azure KeyVault content (secret,certificate or key)"
                        pattern: "(^secret$)|(^certificate$)|(^key$)"
                      copyTo:
                        type: array
                        description: "List of kubernetes secrets which is created with referenced Azure KeyVault contents"
                        items:
                          type: object
                          required: ["namespace", "secretName"]
                          properties:
                            namespace:
                              type: string
                              description: "Namespace of to be created secret"
                            secretName:
                              type: string
                              description: "Name of to be created secret"
                            secretType:
                              type: string
                              description: "Type of to be created secret (default : Opaque)"
                              pattern: "(^[Oo]paque$)|(^kubernetes.io/(service-account-token|dockercfg|dockerconfigjson|basic-auth|ssh-auth|tls)$)|(^bootstrap.kubernetes.io/token$)"
                              default: "Opaque"
      additionalPrinterColumns:
        - name: "syncVersion"
          jsonPath: .spec.syncVersion
          type: integer
        - name: "serviceprincipal-secret-namespace"
          jsonPath: .spec.servicePrincipal.secretNamespace
          type: string
        - name: "serviceprincipal-secret-name"
          jsonPath: .spec.servicePrincipal.secretName
          type: string

