apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-keyvault-secret-operator.fullname" . }}
  labels:
    {{- include "azure-keyvault-secret-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "azure-keyvault-secret-operator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "azure-keyvault-secret-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ include "azure-keyvault-secret-operator.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: logLevel
              value: {{ .Values.configs.logLevel | quote }}
            - name: enableJsonLogging
              value: {{ .Values.configs.enableJsonLogging | quote }}
            - name: reconciliationFrequency
              value: {{ .Values.configs.reconciliationFrequency | quote }}
            {{- if and (hasKey .Values.configs "forceUpdateFrequency") (.Values.configs.forceUpdateFrequency) }}
            - name: forceUpdateFrequency
              value: {{ .Values.configs.forceUpdateFrequency | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
