apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-keyvault-secret-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-keyvault-secret-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: azure-keyvault-secret-operator
    spec:
      serviceAccountName: azure-keyvault-secret-operator
      restartPolicy: Always
      containers:
      - name: operator
        image: btungut/azure-keyvault-secret-operator:1.7.0
        env:
          # valid values: Verbose, Debug, Information, Warning, Error, Fatal (default : Information)
          - name: logLevel
            value: "Information" 
          
          # valid values : true, false (default : false) 
          - name: enableJsonLogging
            value: "false"

          # hh:mm:ss
          - name: reconciliationFrequency
            value: "00:00:30"

          - name: forceUpdateFrequency
            value: "00:03:00"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"

