apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-keyvault-secret-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-keyvault-secret-operator
  template:
    metadata:
      labels:
        app: azure-keyvault-secret-operator
    spec:
      serviceAccountName: azure-keyvault-secret-operator
      restartPolicy: Always
      containers:
      - name: operator
        image: k3s-nonprod-01:5000/operator:3
        env:
          - name: LogLevel
            value: "Debug" # valid values: Verbose, Debug, Information, Warning, Error, Fatal (default : Information)
          - name: EnableJsonLogging
            value: "false" # valid values : true, false (default : false) 
          - name: ReconciliationFrequency
            value: "00:00:30" # hh:mm:ss
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

