apiVersion: btungut.io/v1
kind: AzureKeyVault
metadata:
  name: superstore
spec:
  syncVersion: 1
  azureKeyVaultRef:
    name: superstore-test-29358 # needs to be changed
    resourceGroup: superstore-test
  servicePrincipalRef:
    secretName: "k8s-cluster-azure-identity"
    secretNamespace: "default"
    tenantIdField: "tenantid"
    clientIdField: "clientid"
    clientSecretField: "clientsecret"
  managedSecrets:

    - name: catalog-api
      namespaces:
        - "superstore-test"
      type: Opaque
      data:
        catalogdb-connectionstring: "$['catalogdb']"

    - name: amqp
      namespaces:
        - "(.+)-test"
      type: Opaque
      data:
        amqp-connectionstring: "amqp://$['amqp-username']:$['amqp-password']@brokersvc:5672/"

    - name: docker-registry-credential
      namespaces:
        - "^((?!kube).)*$"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "$['docker-config-json']"