
apiVersion: btungut.io/v1
kind: AzureKeyVault
metadata:
  name: burak
spec:
  name: superstore-test-kv
  resourceGroup: common-rg
  syncVersion: 2
  servicePrincipal:
    secretName: "azure-sp"
    secretNamespace: "infra"
    tenantIdField: "tenantid"
    clientIdField: "clientid"
    clientSecretField: "clientsecret"
  objects:
    - name: catalogdb
      type: secret
      copyTo:
        - namespace: default
          secretName: CatalogDB
          secretType: "kubernetes.io/dockerconfigjson"
        # - namespace: superstore-test
        #   secretName: CatalogDB
    # - name: orderingdb
    #   type: secret
    #   copyTo:
    #     - namespace: default
    #       secretName: OrderingDB
    #     # - namespace: superstore-test
    #     #   secretName: OrderingDB