{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azure-keyvault-secret-operator.clusterRoleName" . }}
  labels:
    {{- include "azure-keyvault-secret-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["namespaces", "namespaces/status"]
    verbs: ["list", "get", "watch"]

  - apiGroups: [btungut.io]
    resources: [azurekeyvaults]
    verbs: [list, watch, patch, get, update]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
{{- end }}
