{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-keyvault-secret-operator.serviceAccountName" . }}
  labels:
    {{- include "azure-keyvault-secret-operator.labels" . | nindent 4 }}
{{- end }}
