apiVersion: v2
name: azure-keyvault-secret-operator
description: Kubernetes operator which enables your cluster to sync secrets with Azure KeyVault in easiest way
type: application
version: 0.0.1
appVersion: "0.0.1"
sources:
  - https://github.com/btungut/azure-keyvault-secret-operator
home: https://github.com/btungut/azure-keyvault-secret-operator
maintainers:
  - name: Burak Tungut
    email: buraktungut@gmail.com

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/license: MIT
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
  artifacthub.io/crds: |
    - kind: AzureKeyVault
      version: v1
      name: azurekeyvault
      displayName: AzureKeyVault
      description: Represents Azure KeyVault reference which is responsible to sync secrets accross cluster.