nameOverride: ""
fullnameOverride: ""

image:
  repository: btungut/azure-keyvault-secret-operator
  tag: 0.0.1

configs:
  LogLevel: "Information"             # valid values: Verbose, Debug, Information, Warning, Error, Fatal (default : Information)
  EnableJsonLogging: "false"          # valid values: true, false as string
  ReconciliationFrequency: "00:00:30" # timespan hh:mm:ss

rbac:
  enabled: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
